version: '3.8'

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
    restart: always

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod
    restart: always

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - 1336:80
    depends_on:
      - web
    restart: always

  celery:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: celery --app=core worker --loglevel=info --logfile=logs/celery.log
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    env_file:
      - ./.env.prod
    depends_on:
      - web
      - redis
    restart: always

  redis:
    image: redis:6-alpine
    restart: always

  dashboard:
    build: ./app
    command:  celery flower -A core --port=5555 --broker=redis://redis:6379/0
    ports:
      - 5666:5555
    env_file:
      - ./.env.prod
    depends_on:
      - web
      - redis
      - celery
    restart: always


volumes:
  postgres_data:
  static_volume:
  media_volume: