# Generated by Django 3.2.12 on 2022-02-12 12:29

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.IntegerField(unique=True, verbose_name='№ счета')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=18, verbose_name='Баланс')),
                ('dateCreate', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания счета')),
                ('dateUpdate', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения счета')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Operations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(max_length=36, unique=True, verbose_name='Номер операции')),
                ('dateCreate', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания операции')),
                ('dateUpdate', models.DateTimeField(auto_now=True, verbose_name='Дата последнего события')),
                ('status', models.CharField(max_length=11, verbose_name='Номер операции')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь отправитель')),
                ('userRecipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь получатель')),
            ],
        ),
        migrations.CreateModel(
            name='Translations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=18, verbose_name='Сумма перевода')),
                ('dateCreate', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания транзакции')),
                ('accountRecipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account+', to='finance.accounts')),
                ('accountSender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account+', to='finance.accounts')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operation+', to='finance.operations')),
            ],
        ),
    ]
